function d4q2_ref = dz4_Ref(t)
%DZ4_REF
%    D4Q2_REF = DZ4_REF(T)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-May-2021 09:54:25

d4q2_ref = pi.*sin(t.*2.0).*8.0;
