function [M,C,G] = MCG(th,dth,in3,in4)
%MCG
%    [M,C,G] = MCG(TH,DTH,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-May-2021 10:00:44

I1 = in3(2,:);
L = in4(:,2);
g = in4(:,1);
m1 = in3(1,:);
M = I1+L.^2.*m1;
if nargout > 1
    C = 0.0;
end
if nargout > 2
    G = L.*g.*m1.*cos(th);
end
