function [q2_ref,dq2_ref,ddq2_ref] = Ref(t)
%REF
%    [Q2_REF,DQ2_REF,DDQ2_REF] = REF(T)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    19-May-2021 09:54:25

t2 = t.*2.0;
t3 = sin(t2);
q2_ref = pi+(t3.*pi)./2.0;
if nargout > 1
    dq2_ref = pi.*cos(t2);
end
if nargout > 2
    ddq2_ref = t3.*pi.*-2.0;
end
