function [M,C,G] = MCG(in1,in2,in3,in4)
%MCG
%    [M,C,G] = MCG(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    26-May-2021 13:57:05

Ip = in4(4,:);
Iw = in4(2,:);
L = in3(:,3);
Lcm = in3(:,2);
g = in3(:,1);
mp = in4(3,:);
mw = in4(1,:);
q1 = in1(1,:);
t2 = L.*mw;
t3 = Lcm.*mp;
M = reshape([Ip+Iw+L.*t2+Lcm.*t3,Iw,Iw,Iw],[2,2]);
if nargout > 1
    C = reshape([0.0,0.0,0.0,0.0],[2,2]);
end
if nargout > 2
    G = [g.*cos(q1).*(t2+t3);0.0];
end
