function [EL_M,EL_C,EL_G] = MCG(th,dth,m1,in4)
%MCG
%    [EL_M,EL_C,EL_G] = MCG(TH,DTH,M1,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    03-Feb-2022 01:40:20

L = in4(2,:);
g = in4(1,:);
EL_M = L.^2.*m1;
if nargout > 1
    EL_C = 0.0;
end
if nargout > 2
    EL_G = -L.*g.*m1.*sin(th);
end
