function [EL_M,EL_C,EL_G] = MCG(in1,in2,in3,in4)
%MCG
%    [EL_M,EL_C,EL_G] = MCG(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    11-Dec-2022 21:27:30

L = in4(2,:);
dth = in2(1,:);
g = in4(1,:);
m1 = in3(1,:);
m2 = in3(2,:);
th = in1(1,:);
t2 = cos(th);
t3 = sin(th);
t4 = L.*m2.*t2;
t5 = -t4;
EL_M = reshape([L.^2.*m2,t5,t5,m1+m2],[2,2]);
if nargout > 1
    EL_C = reshape([0.0,L.*dth.*m2.*t3,0.0,0.0],[2,2]);
end
if nargout > 2
    EL_G = [-L.*g.*m2.*t3;0.0];
end
